// The curated set of shows the tool pages (/how-long-to-watch/ and /countdown/)
// are generated for. Curated on purpose: these are the titles
// people actually search "how long to watch" / "random episode" for, and a
// fixed list keeps the build deterministic and the data folder small.
//
// Each entry is a TVmaze search query. `year` is the premiere year, needed
// whenever the bare name is ambiguous (the 1999 One Piece anime vs. the 2023
// live-action; the US Office vs. the UK one). Add `id` to pin a TVmaze show id
// outright. `name` overrides TVmaze's title for the page heading and URL —
// used where TVmaze lists the Japanese title and people search the English one. To add a show: append a line, run `node scripts/fetch-shows.mjs`,
// and review the table it prints.
export const SHOWS = [
  // --- sitcoms & comedies ---
  { q: "The Office", year: 2005 },
  { q: "Friends" },
  { q: "Seinfeld" },
  { q: "Parks and Recreation" },
  { q: "Brooklyn Nine-Nine" },
  { q: "Community" },
  { q: "The Good Place" },
  { q: "Schitt's Creek" },
  { q: "New Girl" },
  { q: "How I Met Your Mother" },
  { q: "The Big Bang Theory" },
  { q: "Modern Family" },
  { q: "Scrubs", year: 2001 },
  { q: "30 Rock" },
  { q: "Arrested Development" },
  { q: "It's Always Sunny in Philadelphia" },
  { q: "Curb Your Enthusiasm" },
  { q: "Veep" },
  { q: "Silicon Valley" },
  { q: "Abbott Elementary" },
  { q: "Ted Lasso" },
  { q: "Hacks" },
  { q: "What We Do in the Shadows" },
  { q: "Superstore" },
  { q: "Frasier", year: 1993 },
  { q: "Cheers" },
  { q: "That '70s Show" },
  { q: "Malcolm in the Middle" },
  { q: "Gilmore Girls" },
  { q: "Sex and the City" },
  { q: "Entourage" },
  { q: "Insecure" },
  { q: "Fleabag" },
  { q: "Derry Girls" },
  { q: "Ghosts", year: 2021 },
  { q: "Only Murders in the Building" },
  { q: "The Bear" },
  { q: "Never Have I Ever" },
  { q: "Sex Education" },
  { q: "Emily in Paris" },
  { q: "Ginny & Georgia" },
  { q: "Grace and Frankie" },
  { q: "Unbreakable Kimmy Schmidt" },
  { q: "Big Mouth" },
  { q: "BoJack Horseman" },
  { q: "Rick and Morty" },
  { q: "South Park" },
  { q: "Family Guy" },
  { q: "The Simpsons" },
  { q: "Futurama" },
  { q: "Bob's Burgers" },
  { q: "American Dad!" },
  { q: "King of the Hill" },
  { q: "Archer", year: 2009 },
  // --- drama & prestige ---
  { q: "Breaking Bad" },
  { q: "Better Call Saul" },
  { q: "Game of Thrones" },
  { q: "House of the Dragon" },
  { q: "The Sopranos" },
  { q: "The Wire" },
  { q: "Mad Men" },
  { q: "Succession" },
  { q: "The Last of Us" },
  { q: "Euphoria" },
  { q: "The White Lotus" },
  { q: "True Detective" },
  { q: "Westworld" },
  { q: "Barry" },
  { q: "Big Little Lies" },
  { q: "Chernobyl" },
  { q: "Band of Brothers" },
  { q: "The Penguin" },
  { q: "Boardwalk Empire" },
  { q: "Six Feet Under" },
  { q: "Deadwood" },
  { q: "Oz" },
  { q: "The Leftovers" },
  { q: "Shogun", year: 2024, name: "Shogun" },
  { q: "The Handmaid's Tale" },
  { q: "Severance" },
  { q: "Slow Horses" },
  { q: "The Morning Show" },
  { q: "Ozark" },
  { q: "Stranger Things" },
  { q: "Wednesday" },
  { q: "Squid Game" },
  { q: "Bridgerton" },
  { q: "The Witcher" },
  { q: "The Crown" },
  { q: "Money Heist", name: "Money Heist" },
  { q: "Black Mirror" },
  { q: "Outer Banks" },
  { q: "You" },
  { q: "Cobra Kai" },
  { q: "The Umbrella Academy" },
  { q: "Lucifer" },
  { q: "Peaky Blinders" },
  { q: "Narcos" },
  { q: "Dark" },
  { q: "Mindhunter", name: "Mindhunter" },
  { q: "The Queen's Gambit" },
  { q: "Beef", name: "Beef" },
  { q: "Baby Reindeer" },
  { q: "The Night Agent" },
  { q: "Heartstopper" },
  { q: "Shadow and Bone" },
  { q: "Manifest" },
  { q: "Virgin River" },
  { q: "Sweet Tooth" },
  { q: "Orange Is the New Black" },
  { q: "House of Cards", year: 2013 },
  { q: "The Diplomat", year: 2023 },
  { q: "Yellowstone" },
  { q: "1923" },
  { q: "Tulsa King" },
  { q: "Landman" },
  { q: "Mayor of Kingstown" },
  { q: "Grey's Anatomy" },
  { q: "The Walking Dead" },
  { q: "Fear the Walking Dead" },
  { q: "Suits" },
  { q: "Prison Break" },
  { q: "Lost" },
  { q: "House" },
  { q: "Bones" },
  { q: "Criminal Minds" },
  { q: "NCIS" },
  { q: "Law & Order: Special Victims Unit" },
  { q: "Chicago Fire" },
  { q: "Chicago P.D." },
  { q: "9-1-1" },
  { q: "The Rookie" },
  { q: "Dexter" },
  { q: "Sons of Anarchy" },
  { q: "Mad Men" },
  { q: "Twin Peaks" },
  { q: "The X-Files" },
  { q: "Buffy the Vampire Slayer" },
  { q: "Supernatural" },
  { q: "The Vampire Diaries" },
  { q: "The Originals" },
  { q: "One Tree Hill" },
  { q: "Gossip Girl", year: 2007 },
  { q: "Pretty Little Liars" },
  { q: "Riverdale" },
  { q: "The 100" },
  { q: "Vikings" },
  { q: "The Blacklist" },
  { q: "Sherlock" },
  { q: "Doctor Who", year: 2005 },
  { q: "Downton Abbey" },
  { q: "Battlestar Galactica", year: 2004 },
  { q: "Lost in Space", year: 2018 },
  { q: "Fallout" },
  { q: "Reacher" },
  { q: "The Boys" },
  { q: "Invincible" },
  { q: "The Expanse" },
  { q: "Star Trek: Strange New Worlds" },
  { q: "Star Trek: Discovery" },
  { q: "Star Trek: The Next Generation" },
  { q: "Halo" },
  { q: "American Horror Story" },
  { q: "The Mandalorian" },
  { q: "Andor" },
  { q: "Ahsoka" },
  { q: "Loki" },
  { q: "WandaVision" },
  { q: "Moon Knight" },
  { q: "Daredevil", year: 2015, name: "Daredevil" },
  { q: "Percy Jackson and the Olympians" },
  { q: "Star Wars: The Clone Wars" },
  { q: "Bluey" },
  { q: "Gravity Falls" },
  { q: "Phineas and Ferb" },
  { q: "Avatar: The Last Airbender", year: 2005 },
  { q: "The Legend of Korra" },
  { q: "SpongeBob SquarePants" },
  { q: "Adventure Time" },
  { q: "Survivor", year: 2000 },
  { q: "Love Is Blind" },
  { q: "The Great British Bake Off" },
  { q: "RuPaul's Drag Race" },
  // --- anime ---
  { q: "One Piece", year: 1999 },
  { q: "Naruto" },
  { q: "Naruto Shippuden", name: "Naruto Shippuden" },
  { q: "Boruto: Naruto Next Generations" },
  { q: "Bleach" },
  { q: "Dragon Ball Z" },
  { q: "Dragon Ball Super" },
  { q: "Attack on Titan" },
  { q: "Kimetsu no Yaiba", name: "Demon Slayer: Kimetsu no Yaiba" },
  { q: "Jujutsu Kaisen" },
  { q: "My Hero Academia" },
  { q: "Hunter x Hunter", year: 2011 },
  { q: "Fullmetal Alchemist: Brotherhood" },
  { q: "Death Note" },
  { q: "Cowboy Bebop", year: 1998 },
  { q: "Spy x Family", name: "Spy x Family" },
  { q: "Chainsaw Man" },
  { q: "One-Punch Man" },
  { q: "Mob Psycho 100" },
  { q: "Black Clover" },
  { q: "Fairy Tail" },
  { q: "Haikyu!!", name: "Haikyu!!" },
  { q: "Vinland Saga" },
  { q: "Tokyo Ghoul" },
  { q: "Sword Art Online" },
  { q: "Dr. Stone" },
  { q: "Blue Lock" },
  { q: "Solo Leveling" },
  { q: "Frieren: Beyond Journey's End" },
  { q: "Dandadan" },
  { q: "Kaiju No. 8" },
  { q: "Fire Force" },
  { q: "The Promised Neverland" },
  { q: "Re:ZERO -Starting Life in Another World-", name: "Re:Zero - Starting Life in Another World" },
  { q: "Steins;Gate" },
  { q: "Code Geass: Lelouch of the Rebellion", name: "Code Geass: Lelouch of the Rebellion" },
  { q: "Neon Genesis Evangelion" },
  { q: "JoJo's Bizarre Adventure" },
  { q: "Yu Yu Hakusho", id: 4246, name: "Yu Yu Hakusho" },
  { q: "Pokémon" },
  { q: "Sailor Moon", name: "Sailor Moon" },
  { q: "Ranking of Kings", name: "Ranking of Kings" },
  { q: "Oshi no Ko", name: "Oshi no Ko" },
  { q: "Bocchi the Rock!" },
  { q: "Cyberpunk: Edgerunners" },
  { q: "Castlevania" },
  { q: "Arcane", name: "Arcane" },
];
